SERVICE_NAME: "ERC 20 & 721 Tokens API"
PORT: 3000
NETWORK: redB
CONTRACTS:
  - name: AlastriaERC721StructData
    address:
    autoDeploy: false
LOG_LEVELS:
  LOG_LEVEL_SYSTEM: 'debug'
  LOG_LEVEL_FILE: 'info'