SERVICE_NAME: "ERC 20 & 721 Tokens API"
PORT: 3000
NETWORK: hardhat
CONTRACTS:
  - name: AlastriaERC20
    address:
    autoDeploy: false
  - name: AlastriaERC721
    address:
    autoDeploy: false
LOG_LEVELS:
  LOG_LEVEL_SYSTEM: 'debug'
  LOG_LEVEL_FILE: 'info'